SanghaBoutique.Web/ViewModels/WidgetViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SanghaBoutique.Entities;

namespace SanghaBoutique.Web.ViewModels
{
    public class ProductsWidgetViewModel
    {
        public List<Product> Products { get; set; }
        public bool isLatestProducts { get; set; }      
    }
}

SanghaBoutique.Web/Controllers/ProductController.cs
using SanghaBoutique.Entities;
using SanghaBoutique.Services;
using SanghaBoutique.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SanghaBoutique.Web.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductTable(string search, int? pageno)//make pageno nullable
        {
            ProductSearchViewModel model = new ProductSearchViewModel();
            pageno = pageno.HasValue ? pageno.Value > 0 ? pageno.Value : 1 : 1;

            var totalRecords = ProductServices.Instance.GetProductsCount(search);
            model.Products = ProductServices.Instance.GetProducts(search, pageno.Value);

            if (model.Products != null)
            {
                model.Pager = new Pager(totalRecords, pageno, 5);
                return PartialView("ProductTable", model);
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            NewProductViewModel model = new NewProductViewModel();
            model.AvailableCategories = CategoriesServices.Instance.GetAllCategories();
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {
            var newProduct = new Product();
            newProduct.Name = model.Name;
            newProduct.Description = model.Description;
            newProduct.price = model.Price;
            newProduct.ImageURL = model.ImageURL;
            newProduct.Category = CategoriesServices.Instance.GetCategory(model.CategoryID);

            ProductServices.Instance.SaveProducts(newProduct);
            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();
            var product = ProductServices.Instance.GetProduct(ID);
            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.ImageURL = product.ImageURL;
            model.Price = product.price;

            if (product.Category != null)
            {
                model.CategoryID = product.Category.ID;
            }
            else
            {
                model.CategoryID = 0;
            }

            model.AvailableCategories = CategoriesServices.Instance.GetAllCategories();
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            var existingProduct = ProductServices.Instance.GetProduct(model.ID);
            existingProduct.Name = model.Name;
            existingProduct.Description = model.Description;
            existingProduct.price = model.Price;
           
            //existingProduct.CategoryID = 0;
            //existingProduct.CategoryID = model.CategoryID;

            if (!string.IsNullOrEmpty(model.ImageURL))
            {
                existingProduct.ImageURL = model.ImageURL;
            }
            ProductServices.Instance.UpdateProduct(existingProduct);
            return RedirectToAction("ProductTable");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            ProductServices.Instance.DeleteProduct(id);
            return RedirectToAction("ProductTable");
        }
        
        [HttpGet]
        public ActionResult Details(int ID)
        {
            ProductViewModel model = new ProductViewModel();
            model.Product = ProductServices.Instance.GetProduct(ID);
            return PartialView(model);
        }
    }
}

SanghaBoutique.Web/Controllers/WidgetController.cs
using SanghaBoutique.Services;
using SanghaBoutique.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SanghaBoutique.Web.Controllers
{
    public class WidgetController : Controller
    {
        // GET: Widget JAS
        public ActionResult Products(bool isLatestProduct, int? CategoryID=0)
        {
            ProductsWidgetViewModel model = new ProductsWidgetViewModel();
            model.isLatestProducts = isLatestProduct;
            if(isLatestProduct)
            {
                model.Products = ProductServices.Instance.GetLatestProducts(4);
            }
            else if(CategoryID.HasValue && CategoryID.Value>0)
            {
                model.Products = ProductServices.Instance.GetLatestProductsByCategory(CategoryID.Value, 4);
            }
            else
            {
                model.Products = ProductServices.Instance.GetProducts(1, 8);
            }
            return PartialView(model);
        }
    }
}

SanghaBoutique.Web/Views/Widget/Products.cshtml
@model SanghaBoutique.Web.ViewModels.ProductsWidgetViewModel
@{
    var defaultImageURL = "/Content/images/placeholder-image.jpg";
}

@if (Model != null && Model.Products != null)
{
    if (!Model.isLatestProducts)
    {
        <ul class="flat-filter style-1 text-center max-width-682 clearfix">
            <li class="active"><a href="#" data-filter="*">All Product</a></li>

            @foreach (var category in Model.Products.Select(x => x.Category).ToList().Distinct())
            {
                <li><a href="#" data-filter=".@category.Name">For @category.Name</a></li>

            }
        </ul>
        <div class="divider h54"></div>
    }

    <div class="product-content product-fourcolumn clearfix">
        <ul class="product style2 isotope-product clearfix">
            @foreach (var product in Model.Products)
            {
                var imageURL = string.IsNullOrEmpty(product.ImageURL) ? defaultImageURL : product.ImageURL;

                <li class="product-item @product.Category.Name">
                    <div class="product-thumb clearfix">
                        <a href="@Url.Action("Details","Product", new {product.ID})" class="product-thumb">
                            <img src="@imageURL" alt="image" style="width:250px;height:300px;">
                        </a>
                        @if (Model.isLatestProducts == true)
                        {
                            <span class="new">New</span>
                        }
                        else
                        {
                            <span class="new">Sale</span>
                        }
                    </div>
                    <div class="product-info text-center clearfix" style="margin-top:25px">
                        <span class="product-title">
                            @product.Name
                        </span>
                        <div class="price">
                            <ins>
                                <span class="amount">$@product.price</span>
                            </ins>
                        </div>                       
                    </div>
                </li>
            }
        </ul>
    </div>

}