SanghaBoutique.Web/ViewModels/SharedViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SanghaBoutique.Web.ViewModels
{
    public class BaseListingViewModel
    {

    }
    public class Pager
    {
        public Pager(int totalItems, int? page, int pageSize=5)
        {
            if (pageSize == 0) pageSize = 5;

            var totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            var currentPage = page != null ? (int)page : 1;
            var startPage = currentPage - 5;
            var endPage = currentPage + 4;
            if(startPage <= 0)
            {
                endPage -= (startPage - 1);
                    startPage = 1;
            }
            if(endPage > totalPages)
            {
                endPage = totalPages;
                if(endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }
            TotalItems = totalItems;
            CurrentPage = currentPage;
            PageSize = pageSize;
            TotalPages = totalPages;
            StartPage = startPage;
            EndPage = endPage;
        }

        public int TotalItems { get; private set; }
        public int CurrentPage { get; private set; }
        public int PageSize { get; private set; }
        public int TotalPages { get; private set; }
        public int StartPage { get; private set; }
        public int EndPage { get; private set; }
    }
}

SanghaBoutique.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SanghaBoutique.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet; //return during GET request as well

            try
            {
                var file = Request.Files[0];

                //Guid.NewGuid() will create random string - change the name of file for security reason
                // var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var fileName = file.FileName;
                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                //var fileName1 = Guid.NewGuid() + Path.GetExtension(file.FileName);
                //var path1 = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                

                file.SaveAs(path);


                result.Data = new
                {
                    Success = true,
                    ImageURL = string.Format("/content/images/{0}", fileName)
                };
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }
            return result;
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

SanghaBoutique.Web/Controllers/ShopController.cs
using SanghaBoutique.Services;
using SanghaBoutique.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using static SanghaBoutique.Web.Code.Enums;

namespace SanghaBoutique.Web.Controllers
{
    public class ShopController : Controller
    {
        public ActionResult Index(string searchTerm, int? minimumPrice, int? maximumPrice, int? categoryID, int? sortBy, int? pageNo)
        {
            ShopViewModel model = new ShopViewModel();

            model.FeaturedCategories = CategoriesServices.Instance.GetFeaturedCategories();
            model.MaximumPrice = ProductServices.Instance.GetMaximumPrice();
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;


            model.Products = ProductServices.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy, pageNo.Value, 5);
            model.SortBy = sortBy;
            model.CategoryID = categoryID;
            int totalCount = ProductServices.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy);
            model.Pager = new Pager(totalCount, pageNo);
            return View(model);
        }

        public ActionResult FilterProducts(string searchTerm, int? minimumPrice, int? maximumPrice, int? categoryID, int? sortBy, int? pageNo)
        {
            FilterProductViewModel model = new FilterProductViewModel();

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.SortBy = sortBy;
            model.SearchTerm = searchTerm;
            model.CategoryID = categoryID;

            int totalCount = ProductServices.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy);

            model.Products = ProductServices.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy, pageNo.Value, 5);

            model.Pager = new Pager(totalCount, pageNo);

            return PartialView(model);
        }

        [Authorize]
        public ActionResult Checkout()
        {
            CheckoutViewModels cprod = new CheckoutViewModels();
            var CartProductsCookie = Request.Cookies["CartProducts"];
            if (CartProductsCookie != null)
            {
                cprod.CartProductIds = CartProductsCookie.Value.Split('-').Select(x => int.Parse(x)).ToList();
                cprod.CartProducts = ProductServices.Instance.GetProducts(cprod.CartProductIds);
            }
            return View(cprod);
        }

        public ActionResult PlaceOrder()
        {
            HttpCookie currentUserCookie = HttpContext.Request.Cookies["CartProducts"];
            HttpContext.Response.Cookies.Remove("CartProducts");
            if (currentUserCookie != null)
            {
                currentUserCookie.Expires = DateTime.Now.AddDays(-10);
                currentUserCookie.Value = null;
                HttpContext.Response.SetCookie(currentUserCookie);
            }
            return View();
        }
    }
}

SanghaBoutique.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sangha Boutique</title>

    <meta name="author">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/style.css">
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/responsive.css">
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/colors/color1.css" id="colors">
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/animate.css">
    <link href="favicon.ico" rel="shortcut icon">
    <script src="~/Content/javascript/jquery.min.js"></script>
    <script src="~/Content/javascript/jquery.easing.js"></script>
    <script src="~/Content/javascript/jquery-ui.js"></script>
</head>
<body class="header_sticky header-style-1 has-menu-extra">
    <div class="boxed">
        <div id="site-header-wrap">
            <!-- Header -->
            <header id="header" class="header header-container clearfix">
                <div class="container clearfix" id="site-header-inner">
                    <div id="logo" class="logo float-left">
                        <a href="@Url.Action("Index", "Home")" title="logo">
                            <img src="~/Content/images/SanghaLogo.png" alt="image" width="107" height="24" data-retina="~/Content/images/SanghaLogo@2x.png" data-width="107" data-height="24">
                        </a>
                    </div>
                    <div class="mobile-button"><span></span></div>
                    <ul class="menu-extra">
                         <li class="box-cart nav-top-cart-wrapper">
                        <a class="icon_cart nav-cart-trigger active" href="@Url.Action("Checkout", "Shop")"><span id="cartProductsCount"></span></a>
                        </li>
                    </ul>
                    <div class="nav-wrap">
                        <nav id="mainnav" class="mainnav">
                            <ul class="menu">
                                <li class="active">
                                    <a href="@Url.Action("Index", "Home")">HOME</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Shop")">SHOP</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Contact", "Home")">CONTACT</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("AdminLogin", "Account")">ADMIN</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </header>
        </div>
        @RenderBody()
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <p class="copyright text-center">Copyright 2019 <a href="#">Sangha Boutique</a></p>
                    </div>
                </div>
            </div>
        </div>
        <a class="go-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>
    <!-- Javascript -->

    <script src="~/Content/javascript/parallax.js"></script>
    <script src="~/Content/javascript/jquery-waypoints.js"></script>
    <script src="~/Content/javascript/jquery-countTo.js"></script>
    <script src="~/Content/javascript/jquery.countdown.js"></script>
    <script src="~/Content/javascript/jquery.flexslider-min.js"></script>
    <script src="~/Content/javascript/images-loaded.js"></script>
    <script src="~/Content/javascript/bootstrap.min.js"></script>
    <script src="~/Content/javascript/jquery.isotope.min.js"></script>
    <script src="~/Content/javascript/magnific.popup.min.js"></script>
    <script src="~/Content/javascript/jquery.hoverdir.js"></script>
    <script src="~/Content/javascript/owl.carousel.min.js"></script>

    @*<script src="~/Content/javascript/tether.min.js"></script>*@
    <script src="~/Content/javascript/equalize.min.js"></script>
    <script src="~/Content/javascript/gmap3.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAIEU6OT3xqCksCetQeNLIPps6-AYrhq-s&region=GB"></script>
    <script src="~/Content/javascript/jquery-ui.js"></script>

    <script src="~/Content/javascript/jquery.cookie.js"></script>
    <script src="~/Content/javascript/main.js"></script>

    <!-- Revolution Slider -->
    <script src="~/Content/rev-slider/js/jquery.themepunch.tools.min.js"></script>
    <script src="~/Content/rev-slider/js/jquery.themepunch.revolution.min.js"></script>
    <script src="~/Content/javascript/rev-slider.js"></script>
    <!-- Load Extensions only on Local File Systems ! The following part can be removed on Server for On Demand Loading -->
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.actions.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.carousel.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.migration.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.navigation.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.parallax.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.video.min.js"></script>

    @*need internet connection to see sweet alert*@
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</body>
</html>