SanghaBoutique.Web/ViewModels/CategoryViewModels.cs
using SanghaBoutique.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SanghaBoutique.Web.ViewModels
{
    public class CategorySearchViewModel
    {
        public List<Category> Categories { get; set; }
        public string SearchTerm { get; set; }
        public Pager Pager { get; set; }
    }
    public class NewCategoryViewModel
    {
        [Required]
        [MinLength(3), MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(200)]
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public bool isFeatured { get; set; }
   }
    public class EditCategoryViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public bool isFeatured { get; set; }
    }
}

SanghaBoutique.Web/Controllers/CategoryController.cs
using SanghaBoutique.Entities;
using SanghaBoutique.Services;
using SanghaBoutique.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace SanghaBoutique.Web.Controllers
{
  // [Authorize(Roles ="Admin,Manager")] //only admin and manager have authorization to work with category
    public class CategoryController : Controller
    {
        [HttpGet]
        public ActionResult Index() //home page or List 
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(NewCategoryViewModel model)
        {
            if (ModelState.IsValid) 
            {
                var newCategory = new Category();
                newCategory.Name = model.Name;
                newCategory.Description = model.Description;
                newCategory.ImageURL = model.ImageURL;
                newCategory.isFeatured = model.isFeatured;

                CategoriesServices.Instance.SaveCategories(newCategory);
                return RedirectToAction("CategoryTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditCategoryViewModel model = new EditCategoryViewModel();
            var category = CategoriesServices.Instance.GetCategory(ID);
            model.ID = category.ID;
            model.Name = category.Name;
            model.Description = category.Description;
            model.ImageURL = category.ImageURL;
            model.isFeatured = category.isFeatured;

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditCategoryViewModel model)
        {
            var existingCategory = CategoriesServices.Instance.GetCategory(model.ID);
            existingCategory.ID = model.ID;
            existingCategory.Name = model.Name;
            existingCategory.Description = model.Description;
            existingCategory.ImageURL = model.ImageURL;
            existingCategory.isFeatured = model.isFeatured;

            CategoriesServices.Instance.UpdateCategory(existingCategory);

            return RedirectToAction("CategoryTable");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var category = CategoriesServices.Instance.GetCategory(id);
            return View(category);
        }

        [HttpPost]
        public ActionResult Delete(Category category)
        {
            CategoriesServices.Instance.DeleteCategory(category.ID);
            return RedirectToAction("CategoryTable");
        }

        public ActionResult CategoryTable(string search, int? pageNo)
        {
            CategorySearchViewModel model = new CategorySearchViewModel();
            model.SearchTerm = search;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var totalRecords = CategoriesServices.Instance.GetCategoriesCount(search);
            model.Categories = CategoriesServices.Instance.GetCategories(search, pageNo.Value);

            if (model.Categories != null)
            {
                model.Pager = new Pager(totalRecords, pageNo, 3);
                return PartialView("CategoryTable", model);
            }
            else
            {
                return HttpNotFound();
            }
        }
    }
}

SanghaBoutique.Web/Views/Category/CategoryTable.cshtml
@model SanghaBoutique.Web.ViewModels.CategorySearchViewModel
@{
    ViewBag.Title = "CategoryTable";
}

<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Search</label>
                    <input class="form-control" id="searchTxt" name="Search" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row">
                        <div class="col-md-4 pr=0">
                            <button class="btn btn-primary form-control" type="button" id="searchBtn">Search</button>
                        </div>
                        <div class="col-md-4 pr=0">
                            <button class="btn btn-primary form-control" type="button" id="resetBtn">Reset</button>
                        </div>
                        <div class="col-md-4 pr=0">
                            <button class="btn btn-primary form-control" type="button" id="newBtn">New</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="font-weight-bold">Category</th>
                <th class="font-weight-bold">Products</th>
                <th class="font-weight-bold">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cat in Model.Categories)
            {
                <tr>
                    <td>@cat.Name</td>
                    <td>
                        @cat.Product.Count
                    </td>
                    <td>
                        <button class="editBtn btn btn-danger" data-id="@cat.ID">Edit</button>
                        <button class="deleteBtn btn btn-danger" data-id="@cat.ID">Delete</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @if (Model.Pager != null)
    {
        <div class="product-pagination text-center clearfix">
            <ul class="flat-pagination">
                @if (Model.Pager.CurrentPage > 1)
                {
                    <li class="prev">
                        <a href="@Url.Action("Index", "Category", new { pageNo = Model.Pager.CurrentPage - 1 })" class="pageDataLink"><i class="fa fa-angle-left"></i></a>
                    </li>
                }
                @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                    <li class="active"><a href="@Url.Action("Index", "Category", new { pageNo = page })" title="" class="pageDataLink">@page</a></li>
                }
                @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <li class="next">
                        <a href="@Url.Action("Index", "Category", new { pageNo = Model.Pager.CurrentPage + 1 })" class="pageDataLink"><i class="fa fa-angle-right"></i></a>
                    </li>
                }
            </ul>
        </div>
    }

</div>
@{
    var url = @Url.Action("CategoryTable", "Category"); //action,controller
}
<script>
    $("#searchBtn").click(function () {
        var searchValue = $("#searchTxt").val();

        //make ajax call to search product without reloading the page
        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")',
            data: {
                search: searchValue
            }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (xMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });
    });

    $("#newBtn").click(function () {
        //make ajax call to create new product without reloading the page
        $.ajax({
            url:   '@Url.Action("Create", "Category")',
        })
            .done(function (response) {
                $("#actionContainer").html(response);
                focusAction("actionContainer");
            })
            .fail(function (xMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });
    });

    $(".editBtn").click(function () {
         $.ajax({
            url: '@Url.Action("Edit", "Category")',
            data: {
                Id: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                $("#actionContainer").html(response);
                focusAction("actionContainer");
            })
            .fail(function (xMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });
    });

     $(".deleteBtn").click(function () {
        //Below Code from sweetalert.js website
        swal({
            title: "Confirm",
            text: "Are you sure want to delete this category?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: 'POST', //because we don't want it to hit GET version of Delete method plus send data
                        url: '@Url.Action("Delete", "Category")',
                        data: {
                            Id: $(this).attr('data-id')
                        }
                    })
                        .done(function (response) {
                            $("#tableContainer").html(response);
                            swal("Poof! Your category has been deleted!", {
                                icon: "success",
                            });
                        })
                        .fail(function (xMLHttpRequest, textStatus, errorThrown) {
                            alert("Failed");
                        });
                }
            });
    });

     $("#resetBtn").click(function () {
         var searchValue = '';
       $.ajax({
            url:'@Url.Action("CategoryTable", "Category")',
            data: {
                search: searchValue
            }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (xMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });
    });

     $(".pageBtn").click(function () {
       $.ajax({
            url:'@Url.Action("CategoryTable", "Category")',
            data: {
                pageNo: $(this).attr("data-pageno"),
                search: '@Model.SearchTerm'
            }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (xMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });
    });
</script>

SanghaBoutique.Web/Views/Category/Create.cshtml
@{
    ViewBag.Title = "Create";//Name of method in the controller
      var imageURL = "/Content/images/placeholder-image.jpg";
}

<h2>Create Category</h2>

<form id="createCategory">
    <div class="form-group">
        <label>Name:<span class="text-danger"></span></label>
        <input class="form-control" name="Name" required/> <!--Name is the property of Category class-->
    </div>
    <div class="form-group">
        <label>Description:</label>
        <input class="form-control" name="Description" />
    </div>  
    <div class="form-group">
        <label>Image:</label>
        <input id="imageURL" name="ImageURL" type="hidden" value="@imageURL" />
        <input id="imageUpload" name="Image" type="file" accept=".png,.jpg" />
    </div>
    <div class="thumb">
        <img id="categoryImage" class="img-thumbnail img-fluid" src="@imageURL" />
    </div>
    <div>
        <label>Is Featured?</label>
        <input name="isFeatured" type="radio" value="true" checked />True
        <input name="isFeatured" type="radio" value="false" />False
    </div>
    <button id="saveBtn" type="button" class="btn btn-primary">Save</button>
    <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
</form>

<script>
    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");

        focusAction("tableContainer");
    });

    
    $("#imageUpload").change(function () {
        var element = this; //imageUpload is the element
        var formData = new FormData(); //to add data - image
        var totalFiles = element.files.length; //number of files - by default u can select one file only
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file); //add image to form data
        }

        $.ajax({
            type: "POST",
            url:  '@Url.Action("UploadImage", "shared")',              
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
            .done(function (response) {
                console.log(response);
                if (response.Success) {
                    $("#imageURL").val(response.ImageURL);                       
                    $("#categoryImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");
        });      
    });


    $('#createCategory').validate({
        rules: {
            Name: {
                required: true,
                minlength: 3,
                maxlength: 50
            },
            Description: {
               maxlength: 200
            }
        },
        messages: {
            Name: {
                required: 'Name is required',
                minlength: 'Minimum length is 3',
                maxlength: 'Maximum Length is 50'
            },
            Description: {
                maxlength: 'Maximum length is 200'
            }
        }
    });

    $("#saveBtn").click(function () {
        if ($("#createCategory").valid()){      
            $.ajax({
                type: 'Post',
                url: '@Url.Action("Create", "Category")',
                data: $("#createCategory").serialize() //serialize all the data from form
            })
                .done(function (response) {
                    $("#tableContainer").html(response);
                    $("#actionContainer").html("");
                    focusAction("tableContainer");
                })
                .fail(function (xMLHttpRequest, textStatus, errorThrown) {
                    swal({
                        title: "Warning",
                        text: "Please enter all required fields.",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                });
        }
        else {
            swal({
                title: "warning",
                text: "Please enter all required fields.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
        }
    });
</script>

SanghaBoutique.Web/Views/Category/Delete.cshtml
@model SanghaBoutique.Entities.Category
@{
    ViewBag.Title = "Delete";
}

<h2>Delete Category</h2>

<h1>Are you sure u want to delete this Category?</h1>
<form method="post">

    <input type="hidden" name="ID" value="@Model.ID" />
   
    <button type="submit">Yes Delete</button>
</form>
<a href="/Index">Cancel</a>

SanghaBoutique.Web/Views/Category/Edit.cshtml
@model SanghaBoutique.Web.ViewModels.EditCategoryViewModel

@{
    ViewBag.Title = "Edit";
    var trueChecked = Model.isFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.isFeatured ? "checked" : string.Empty;

    var img = !string.IsNullOrEmpty(@Model.ImageURL) ? @Model.ImageURL : "/Content/images/placeholder-image.jpg";
}

<h2>Edit Category</h2>

<form id="editCategory">
    <input type="hidden" name="ID" value="@Model.ID" />
    <div class="form-group">
        <label>Name:</label>
        <input class="form-control" name="Name" value="@Model.Name" /> <!--Name is the property of Category class-->
    </div>
    <div class="form-group">
        <label>Description:</label>
        <input class="form-control" name="Description" value="@Model.Description" />
    </div>
    <div class="form-group">
        <label>Image:</label>
        <input id="imageURL" name="ImageURL" type="hidden" value="@Model.ImageURL" />
        <input id="imageUpload" name="Image" type="file" accept=".png,.jpg" />
    </div>
    <div class="thumb">
        <img id="categoryImage" class="img-thumbnail img-fluid" src="@img" />
    </div>

    <div class="form-group">
        <label>Is Featured?</label>
        <input name="isFeatured" type="radio" value="True" @trueChecked />True
        <input name="isFeatured" type="radio" value="False" @falseChecked />False
    </div>
    <button id="updateBtn" type="button" class="btn btn-primary">Update</button>
    <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
</form>

<script>
    $("#imageUpload").change(function () {
        var element = this; //imageUpload is the element
        var formData = new FormData(); //to add data - image
        var totalFiles = element.files.length; //number of files - by default u can select one file only
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file); //add image to form data
        }

        $.ajax({
            type: "POST",
            url: '@Url.Action("UploadImage", "shared")',  
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
            .done(function (response) {
                console.log(response);
                if (response.Success) {
                    $("#imageURL").val(response.ImageURL);
                    $("#categoryImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });
    $("#updateBtn").click(function () {
       $.ajax({
            type: 'Post',
            url:'@Url.Action("Edit", "Category")',   
            data: $("#editCategory").serialize() 
        })
            .done(function (response) {
                $("#tableContainer").html(response);
                $("#actionContainer").html("");
            })
            .fail(function (xMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });

        focusAction("tableContainer");
    });

    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");

        focusAction("tableContainer");
    });

    $('#editCategory').validate({
        rules: {
            Name: {
                required: true,
                minlength: 3,
                maxlength: 50
            },
            Description: {
                maxlength: 200
            }
        },
        messages: {
            Name: {
                required: 'Name is required',
                minlength: 'Minimum length is 3',
                maxlength: 'Maximum Length is 50'
            },
            Description: {
                maxlength: 'Maximum length is 200'
            }
        }
    });
</script>

SanghaBoutique.Web/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<script src = "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js" ></script>

<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Categories
                    </h2>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="container">
    <div id="tableContainer">
        @{
            Html.RenderAction("CategoryTable");
        }
    </div>    
    <div id="actionContainer">
        @*show the form to enter data when you click "New" or"Edit" button*@
    </div>
</div>
<script>
    function focusAction(controlToFocus) {
        $('html, body').animate({
            scrollTop: $("#" + controlToFocus).offset().top - 100
        }, 1000);
    }
</script>